{
  "openapi": "3.0.3",
  "info": {
    "title": "Fly Delivery",
    "description": "This application offers a seamless and convenient way to satisfy your cravings with just a few clicks. Fly-Delivery connects you with a wide range of restaurants and cuisines, bringing delicious meals straight to your doorstep."
  },
  "servers": [
    {
      "url": "http://localhost:4444/"
    }
  ],
  "tags": [
    {
      "name": "auth",
      "description": "Authorization Users"
    },
    {
      "name": "users",
      "description": "Users Operations"
    },
    {
      "name": "articles",
      "description": "Articles Operations"
    },
    {
      "name": "orders",
      "description": "Orders Operations"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Login user",
        "description": "Login user",
        "operationId": "LoginUser",
        "requestBody": {
          "description": "Login user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Bad request!"
          },
          "401": {
            "description": "Unauthorized!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        },
        "required": true
      }
    },
    "/auth/requestResetPassword": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Request reset password user",
        "description": "send request to reset password",
        "operationId": "requestPassword",
        "requestBody": {
          "description": "Request reset password",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Please check your email for reset your password!"
          },
          "404": {
            "description": "Not Found!"
          },
          "444": {
            "description": "No Response!"
          }
        }
      }
    },
    "/auth/resetPassword": {
      "patch": {
        "tags": [
          "auth"
        ],
        "summary": "Reset user Password",
        "description": "Reset user Password",
        "operationId": "ResetUserPassword",
        "requestBody": {
          "description": "Reset user Password",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userId": {
                    "type": "string",
                    "example": "110eb998dfcbe64e756ac4c4"
                  },
                  "token": {
                    "type": "string",
                    "example": "string"
                  },
                  "password": {
                    "type": "string",
                    "example": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Your password has been changed successfully"
          },
          "400": {
            "description": "You have entered an actual password. Please enter a new password or log in again using the same password."
          },
          "401": {
            "description": "Invalid token!"
          },
          "404": {
            "description": "Request user not exist!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Register new user",
        "description": "Register new user",
        "operationId": "regsterNewUser",
        "requestBody": {
          "description": "Register new user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "exemple"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "exemple@email.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "example": "*******"
                  },
                  "role": {
                    "type": "string",
                    "example": "Customer"
                  },
                  "phone": {
                    "type": "string",
                    "example": "00 000 000"
                  },
                  "adress": {
                    "type": "string",
                    "example": "example"
                  },
                  "avatar": {
                    "type": "string",
                    "example": "example"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "Bad request! Email already exist!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Get the list of all users",
        "description": "Get the list of all users",
        "operationId": "ListUsers",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of items per page",
            "required": true,
            "type": "integer"
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Field to sort by",
            "required": true,
            "type": "string"
          },
          {
            "name": "createdAtBefore",
            "in": "query",
            "description": "Filter users created before this date (YYYY-MM-DD format)",
            "required": true,
            "type": "string"
          },
          {
            "name": "createdAtAfter",
            "in": "query",
            "description": "Filter users created after this date (YYYY-MM-DD format)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successfuly operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 1
                    },
                    "totalUsers": {
                      "type": "integer",
                      "example": 1
                    },
                    "users": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "string",
                          "name": "string",
                          "email": "exemple@email.com",
                          "phone": "00 000 000",
                          "role": "customer",
                          "avatar": "string",
                          "statusAccount": true,
                          "adress": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Users not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users/validationAccountClient": {
      "patch": {
        "tags": [
          "users"
        ],
        "summary": "Validation account client",
        "description": "Validation account client.",
        "operationId": "ValidationAccountClinet",
        "requestBody": {
          "description": "Validated your account.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Your account is verify now"
          },
          "400": {
            "description": "Validation code is wrong!"
          },
          "404": {
            "description": "User not found !"
          },
          "409": {
            "description": "Your account is already validated!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users/confirmAccount/{id}": {
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Confirm account Restaurant & Deliveryman",
        "description": "Confirm account Restaurant & Deliveryman.",
        "operationId": "confirmAccount",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation Account Confirmed"
          },
          "401": {
            "description": "Invalid request"
          },
          "403": {
            "description": "Access denied!"
          },
          "404": {
            "description": "User not found !"
          },
          "409": {
            "description": "Bad request! Your account is already verified!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users/request": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Get the list of all users unvalidated",
        "description": "Get the list of all users unvalidated.",
        "operationId": "listUsersUnvalidated",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of items per page",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "successfuly operation ",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 1
                    },
                    "totalUsers": {
                      "type": "integer",
                      "example": 1
                    },
                    "users": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "string",
                          "name": "string",
                          "email": "exemple@email.com",
                          "phone": "00 000 000",
                          "role": "customer",
                          "avatar": "string",
                          "statusAccount": false,
                          "adress": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "There are no unvalidated users!"
          },
          "404": {
            "description": "Users not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Display user profile",
        "description": "Display user profile",
        "operationId": "DisplayUserProfile",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "description": "User not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Delete user",
        "description": "Delete user",
        "operationId": "DeleteUsers",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The user ID that needs to be deleted",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User is successfuly deleted"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/users/password/change": {
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "users"
        ],
        "summary": "Change user password",
        "description": "Change user password",
        "operationId": "changeUserPassword",
        "requestBody": {
          "description": "Change user password",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "actualPassword": {
                    "type": "string",
                    "example": "actualPassword"
                  },
                  "newPassword": {
                    "type": "string",
                    "example": "newPassword"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "newPassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Password has been changed"
          },
          "400": {
            "description": "Bad request! Current password is not correct!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "User not exist !"
          },
          "406": {
            "description": "Password is not confirm!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/restaurant/articles": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Add new article",
        "description": "Add new article",
        "operationId": "AddArticle",
        "requestBody": {
          "description": "Add new article",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Pizza"
                  },
                  "picture": {
                    "type": "string",
                    "example": "pizzapicture"
                  },
                  "price": {
                    "type": "integer",
                    "example": 40
                  },
                  "rating": {
                    "type": "integer",
                    "default": 0
                  },
                  "reviews": {
                    "type": "integer",
                    "default": 0
                  },
                  "information": {
                    "type": "string",
                    "example": "Sauce + mozarella + frites "
                  },
                  "discount": {
                    "type": "integer",
                    "example": 40
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Article created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
          "404": {
            "description": "Bad request!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Delete all articles created by the same restaurant",
        "description": "Delete all articles created by the same restaurant",
        "operationId": "DeleteAllArticles",
        "responses": {
          "200": {
            "description": "Your articles are deleted"
          },
          "400": {
            "description": "Bad request!"
          },
          "404": {
            "description": "You have no articles"
          }
        }
      }
    },
    "/articles": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Get the list of all articles to the customer",
        "description": "Get the list of all articles",
        "operationId": "ListAllArticles",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of items per page",
            "required": true,
            "type": "integer"
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Field to sort by",
            "required": true,
            "type": "string"
          },
          {
            "name": "minPrice",
            "in": "query",
            "description": "Filter articles with price greater or equal",
            "required": true,
            "type": "string"
          },
          {
            "name": "maxPrice",
            "in": "query",
            "description": "Filter articles with price less or equal",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successfuly operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 1
                    },
                    "totalArticles": {
                      "type": "integer",
                      "example": 1
                    },
                    "articles": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "665a072f9cb36aa8375e3c01",
                          "restaurantId": "66429b84caaf6f4270b0254b",
                          "name": "Pizza Napolitaine",
                          "picture": "pizzapicture",
                          "price": 40,
                          "rating": 0,
                          "reviews": 0,
                          "discount": 10,
                          "information": "Sauce + mozarella"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid price range!"
          },
          "404": {
            "description": "There are no article!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    }, 
    "/articles/{id}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Get an article whose identifier is known",
        "description": "Get an article whose identifier is known",
        "operationId": "GetArticle",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
          "404": {
            "description": "Article not found !"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/restaurant/articles/{id}": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Update article whose identifier is known",
        "description": "Update article whose identifier is known",
        "operationId": "UpdateArticle",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The article that needs to updated",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Article with new properties",
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "restaurantId": {
                    "type": "string",
                    "example": "66063369f5a2397ad3b4fa5d"
                  },
                  "name": {
                    "type": "string",
                    "example": "Pizza"
                  },
                  "picture": {
                    "type": "string",
                    "example": "picture of this article"
                  },
                  "price": {
                    "type": "integer",
                    "example": 20
                  },
                  "rating": {
                    "type": "integer",
                    "example": 1
                  },
                  "reviews": {
                    "type": "integer",
                    "example": 10
                  },
                  "discount": {
                    "type": "integer",
                    "example": 30
                  },
                  "information": {
                    "type": "string",
                    "example": "all information about this article"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Article updated ",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "restaurantId": {
                      "type": "string",
                      "example": "66063369f5a2397ad3b4fa5d"
                    },
                    "name": {
                      "type": "string",
                      "example": "Pizza"
                    },
                    "picture": {
                      "type": "string",
                      "example": "picture of this article"
                    },
                    "price": {
                      "type": "integer",
                      "example": 20
                    },
                    "rating": {
                      "type": "integer",
                      "example": 1
                    },
                    "reviews": {
                      "type": "integer",
                      "example": 10
                    },
                    "discount": {
                      "type": "integer",
                      "example": 30
                    },
                    "information": {
                      "type": "string",
                      "example": "all information about this article"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request!"
          },
          "404": {
            "description": "not found"
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Delete article whose identifier is known",
        "description": "Delete article whose identifier is known",
        "operationId": "deleteArticle",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The article that needs to be deleted",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Article is successfuly deleted"
          },
          "400": {
            "description": "Bad request!"
          },
          "401": {
            "description": "Unauthorized! Invalid token"
          },
          "404": {
            "description": "Article not found!"
          }
        }
      }
    },
    "/restaurant/{name}/articles/myarticles": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "articles"
        ],
        "summary": "Get all article created by the same restaurant",
        "description": "Get all article created by the same restaurant",
        "operationId": "GetArticleByRestaurant",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of items per page",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "successfuly operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 1
                    },
                    "totalArticles": {
                      "type": "integer",
                      "example": 1
                    },
                    "articles": {
                      "type": "array",
                      "example": [
                        {
                          "_id": "665a072f9cb36aa8375e3c01",
                          "restaurantId": "66429b84caaf6f4270b0254b",
                          "name": "Pizza Napolitaine",
                          "picture": "pizzapicture",
                          "price": 40,
                          "rating": 0,
                          "reviews": 0,
                          "discount": 10,
                          "information": "Sauce + mozarella"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "You have no article yet"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/orders/{id}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Add new Order",
        "description": "Add new Order",
        "operationId": "AddOrder",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The article ID",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Add new Order",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "numberPieces": {
                    "type": "integer",
                    "example": 2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Article created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
          "404": {
            "description": "Bad request!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "You can change number of pieces",
        "description": "Change number of pieces",
        "operationId": "changeNbrPieces",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order that needs to updated",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Order with new number of pieces",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "numberPieces": {
                    "type": "integer",
                    "example": 2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200":{
            "description": "Order updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "numberPieces": {
                      "type": "integer",
                      "example": 2
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Order not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Delete order",
        "description": "Delete order",
        "operationId": "deleteOrder",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order that needs to be deleted",
            "required": true
          }
        ], 
        "responses": {
          "200": {
            "description": "Order is successfully deleted"
          },
          "400": {
            "description": "Bad request!"
          },
          "404": {
            "description": "Order not found!"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Get all orders and orders created by the same user OR received at the same restaurant OR available to the deliveryman",
        "description": "Get all orders and orders created by the same user OR received at the same restaurant OR available to the deliveryman",
        "operationId": "getAllOrders",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of orders per page",
            "required": true,
            "type": "integer"
          },
          {
            "name": "sortBy (fill in by admin)",
            "in": "query",
            "description": "Field to sort by",
            "required": false,
            "type": "string"
          },
          {
            "name": "createdAtBefore (fill in by admin)",
            "in": "query",
            "description": "Filter orders created before this date (YYYY-MM-DD format)",
            "required": false,
            "type": "string"
          },
          {
            "name": "createdAtAfter (fill in by admin)",
            "in": "query",
            "description": "Filter orders created after this date (YYYY-MM-DD format)",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successfully operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "exemple": true
                    },
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 10
                    },
                    "listOrders": {
                      "type": "integer",
                      "example": 1
                    },
                    "orders": {
                      "type": "array",
                      "example": [
                        {
                        "_id": "66aa509cbe3698c873106862",
                        "articleId": "666b776b78b0808b9a7d8d70",
                        "clientId": "666b76561c55c46db252635f",
                        "restaurantId": "666b769c464843e905f67165",
                        "restaurantStatus": null,
                        "deliverymanStatus": false,
                        "orderStatus": false,
                        "numberPieces": 1,
                        "pricePieces": 9000,
                        "priceOrder": 9000,
                        "createdAt": "2024-07-31T14:56:28.211Z",
                        "updatedAt": "2024-07-31T14:56:28.211Z",
                        "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "No orders yet in this period"
          },
          "404": {
            "description": "Orders not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "delete": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Delete all orders created by the same customer",
        "description": "Delete all orders created by the same customer",
        "operationId": "deleteOrdersCustomer",
        "responses": {
          "200": {
            "description": "All your orders are deleted"
          },
          "404": {
            "description": "You have not yet an order!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/orders/restaurant/{id}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Make the order decision by the restaurant",
        "description": "Make the order decision by the restaurant",
        "operationId": "orderDecisionRestaurant",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order that needs to answer",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Decision of order",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "boolean",
                    "example": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Your answer is sent successfully"
          },
          "404": {
            "description": "Order not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      },
      "patch": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Change the order decision by the restaurant",
        "description": "Change the order decision by the restaurant",
        "operationId": "changeOrderDecision",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order that needs to change the decision",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Change decision of order",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "boolean",
                    "example": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Your answer is sent successfully"
          },
          "400": {
            "description": "Your cannot change your decision!"
          },
          "404": {
            "description": "Order not found!"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/orders/deliveryman/{id}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Make the order decision by the deliveryman",
        "description": "Make the order decision by the deliveryman",
        "operationId": "orderDecisionDeliveryman",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order that needs to answer",
            "required": true
          }
        ],
        "requestBody": {
          "description": "Decision of order",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "decision": {
                    "type": "boolean",
                    "example": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Your answer is sent successfully"
          },
          "404": {
            "description": "There are no orders available yet"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    } ,
    "/orders/deliveryman/history": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "orders"
        ],
        "summary": "Get the history of orders accepted",
        "description": "Get the history of orders accepted",
        "operationId": "historyOrdersAccepted",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number",
            "required": true,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of orders accepted per page",
            "required": true,
            "type": "integer"
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Field to sort by",
            "required": true,
            "type": "string"
          },
          {
            "name": "createdAtBefore",
            "in": "query",
            "description": "Filter history created before this date (YYYY-MM-DD format)",
            "required": true,
            "type": "string"
          },
          {
            "name": "createdAtAfter",
            "in": "query",
            "description": "Filter history created after this date (YYYY-MM-DD format)",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successfully operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "exemple": true
                    },
                    "page": {
                      "type": "integer",
                      "example": 1
                    },
                    "limit": {
                      "type": "integer",
                      "example": 10
                    },
                    "listOrders": {
                      "type": "integer",
                      "example": 1
                    },
                    "orders": {
                      "type": "array",
                      "example": [
                        {
                        "_id": "66aa509cbe3698c873106862",
                        "articleId": "666b776b78b0808b9a7d8d70",
                        "clientId": "666b76561c55c46db252635f",
                        "restaurantId": "666b769c464843e905f67165",
                        "restaurantStatus": true,
                        "deliverymanStatus": true,
                        "orderStatus": true,
                        "numberPieces": 1,
                        "pricePieces": 9000,
                        "priceOrder": 9000,
                        "createdAt": "2024-07-31T14:56:28.211Z",
                        "updatedAt": "2024-07-31T14:56:28.211Z",
                        "__v": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "There are no orders accepted"
          },
          "500": {
            "description": "Internal Server Error!"
          }
        }
      }
    },
    "/orders/pay/{id}": {
        "patch": {
            "security": [
                {
                    "Bearer": []
                }
            ],
            "tags": [
                "orders"
            ],
            "summary": "Payed the order by the customer",
            "description": "Payed the order by the customer",
            "operationId": "paymentCustomer",
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "The order that the customer is to be paid for",
                    "required": true
                }
            ],
            "requestBody": {
                "description": "Confrim the payment",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "paid"
                                },
                                "email_address": {
                                    "type": "string",
                                    "example": "customer@email.com"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200": {
                    "description": "Successful operation ",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "status": {
                                        "type": "number",
                                        "example": 200
                                    },
                                    "success": {
                                        "type": "boolean",
                                        "example": true
                                    },
                                    "message": {
                                        "type": "string",
                                        "example": "Paid Order!"
                                    },
                                    "order": {
                                        "type": "object",
                                        "$ref": "#/components/schemas/Order"
                                    }
                                }
                            }
                        }
                    }
                },
                "404": {
                    "description": "Order not found!"
                },
                "500": {
                    "description": "Internal Server Error!"
                }
            }
        }
    } 
  },
  "components": {
    "schemas": {
      "User": {
        "required": [
          "name",
          "email",
          "password",
          "role",
          "phone",
          "adress",
          "avatar",
          "statusAccount"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "exemple"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "exemple@email.com"
          },
          "password": {
            "type": "string",
            "format": "password",
            "example": "*******"
          },
          "role": {
            "type": "string",
            "example": "Customer",
            "enum": [
              "Restaurant",
              "Deliveryman",
              "Customer"
            ]
          },
          "phone": {
            "type": "integer",
            "example": 12345678
          },
          "adress": {
            "type": "string",
            "example": "example"
          },
          "avatar": {
            "type": "string",
            "example": "example"
          }
        }
      },
      "Article": {
        "required": [
          "restaurantId",
          "name",
          "price",
          "information"
        ],
        "type": "object",
        "properties": {
          "restaurantId": {
            "type": "string",
            "example": "66063369f5a2397ad3b4fa5d"
          },
          "name": {
            "type": "string",
            "example": "Pizza"
          },
          "picture": {
            "type": "string",
            "example": "picture of this article"
          },
          "price": {
            "type": "integer",
            "example": 20
          },
          "rating": {
            "type": "integer",
            "example": 1
          },
          "reviews": {
            "type": "integer",
            "example": 10
          },
          "discount": {
            "type": "integer",
            "example": 30
          },
          "information": {
            "type": "string",
            "example": "all information about this article"
          }
        }
      },
      "Order": {
        "required": [
          "articleId",
          "clientId",
          "restaurantId",
          "numberPieces",
          "pricePieces",
          "priceOrder",
          "shippingPrice",
          "taxPrice"
        ],
        "type": "object",
        "properties": {
          "articleId": {
            "type": "string",
            "example": "66063369f5a2397ad3b4fa5d"
          },
          "clientId": {
            "type": "string",
            "example": "66063369f5a2397ad3b4fa5d"
          },
          "restaurantId": {
            "type": "string",
            "example": "66063369f5a2397ad3b4fa5d"
          },
          "deliverymanId": {
            "type": "string",
            "example": "66063369f5a2397ad3b4fa5d"
          },
          "restaurantStatus": {
            "type": "boolean",
            "example": "true"
          },
          "deliverymanStatus": {
            "type": "boolean",
            "example": "true"
          },
          "orderStatus": {
            "type": "boolean",
            "example": "true"
          },
          "numberPieces": {
            "type": "integer",
            "example": 1
          },
          "pricePieces": {
            "type": "integer",
            "example": 1
          },
          "priceOrder": {
            "type": "integer",
            "example": 10
          },
          "shippingAddress": {
              "required": [
                  "fullName",
                  "address",
                  "phone",
                  "city",
                  "postalCode",
                  "country"
              ],
              "type": "object",
              "properties": {
                  "fullName": {
                      "type": "string",
                      "example": "Full Name"
                  },
                  "address": {
                      "type": "string",
                      "example": "Full Adress"
                  },
                  "phone": {
                      "type": "number",
                      "example": 1234567890
                  },
                  "city": {
                      "type": "string",
                      "example": "Tunis"
                  },
                  "postalCode": {
                      "type": "string",
                      "example": "1000"
                  },
                  "country": {
                      "type": "string",
                      "example": "Tunisia"
                  },
                  "location": {
                      "type": "object",
                      "properties": {
                          "lat": {
                              "type": "number",
                              "example": 40.7128
                          },
                          "lng": {
                              "type": "number",
                              "example": -74.0060
                          },
                          "address": {
                              "type": "string",
                              "example": "Tunis, Tunisia"
                          },
                          "name": {
                              "type": "string",
                              "example": "Home"
                          },
                          "vicinity": {
                              "type": "string",
                              "example": "Near Central Park"
                          },
                          "googleAddressId": {
                              "type": "string",
                              "example": "ChIJOwg_06VPwokRYv534QaPC8g"
                          }
                      }
                  }
              },
              "paymentMethod": {
                  "type": "string",
                  "example": "Cash"
              },
              "isPaid": {
                  "type": "boolean",
                  "example": true
              },
              "isDelivered": {
                  "type": "boolean",
                  "example": false
              },
              "paymentResult": {
                  "type": "object",
                  "properties": {
                      "id": {
                          "type": "string",
                          "example": "PAYID-LXHD6RQ4J5374582K7514701"
                      },
                      "status": {
                          "type": "string",
                          "example": "Completed"
                      },
                      "update_time": {
                          "type": "string",
                          "example": "2023-08-17T12:34:56Z"
                      },
                      "email_address": {
                          "type": "string",
                          "example": "example@example.com"
                      },
                      "paidAt": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2023-08-17T14:00:00Z"
                      }
                  }
              }
          }
        }
      }
    },
    "requestBodies": {
      "User": {
        "description": "List of user object",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/User"
            }
          }
        }
      },
      "Article": {
        "description": "List of articles object",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Article"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "name": "authorization",
        "in": "header"
      }
    }
  }
}